title: FOSS IIITA
description: Promoting Open Source
author: GeekHaven
logo: /static/img/avatar.png
github: https://github.com/fossiiita/
about: IIIT Allahabad

baseurl: ""
url: "https://codeasashu.github.io/hcz-jekyll-blog"

disqus_shortname:
google_analytics:

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
