title: Nybles
description: Tech Newsletter of IIIT Allahabad
author: Nybles
logo: /nybles.github.io/static/img/avatar.png
github: https://github.com/nybles
about: IIIT Allahabad

baseurl: "/"
url: "https://nybles.github.io/"

theme_color: "#006064"
theme_highlight_color: "#00838f"

comments: true

disqus_shortname: geekhaven-blog
google_analytics:

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
